# Release Drafter configuration for universal-dj-usb
# Drafts a GitHub release when a tag is pushed (your `release.sh` creates tags).

name-template: "v$NEXT_PATCH_VERSION"
tag-template: "$TAG"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
no-changes-template: |
  - No notable changes

categories:
  - title: "🚀 Added"
    labels:
      - feature
      - enhancement
  - title: "🐛 Fixed"
    labels:
      - bug
  - title: "🧰 Maintenance"
    labels:
      - chore
      - ci
      - refactor
  - title: "⚡ Performance"
    labels:
      - perf
  - title: "🔒 Security"
    labels:
      - security

template: |
  ## What's Changed
  $CHANGES

  ---
  _This release draft was generated automatically by release-drafter._

# Options you can customize later:
# - add `replaces` to map custom tag patterns
# - enable `prerelease` if you want certain tags to be prereleases
# - tune categories/labels to match your repository's labels
