name: Build

on:
  push:
    tags: ["v*"] # Build on version tags
  pull_request:
    branches: [main]
  workflow_dispatch: # manual

env:
  APP_NAME: "Universal DJ USB"
  PYTHON_VERSION: "3.11"

jobs:
  # Run tests first
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run tests
        run: uv run pytest

  # Build for macOS (both architectures)
  build:
    needs: test
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS Intel build
          - os: macos-13
            target: macos-x64
            arch: x64
          # macOS Apple Silicon build
          - os: macos-14
            target: macos-arm64
            arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --all-extras

      # Build using the build script (which handles its own dependency installation)
      - name: Build executables
        run: |
          # Calculate BUILD_ID for consistent naming
          VERSION=$(uv run python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            BUILD_ID="${VERSION}"
          elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            BUILD_ID="${VERSION}-pr${{ github.event.number }}"
          else
            BUILD_ID="${VERSION}-dev"
          fi
          export BUILD_ID

          chmod +x build.sh
          ./build.sh --both --skip-tests

      # Check build results and sizes
      - name: Check bundle sizes
        run: |
          echo "=== Build Results for ${{ matrix.target }} ==="
          ls -la dist/ || echo "No dist directory"

          [ -f "dist/udj" ] && echo "CLI size: $(ls -lh dist/udj | awk '{print $5}')"
          [ -d "dist/${{ env.APP_NAME }}.app" ] && echo "GUI app size: $(du -sh "dist/${{ env.APP_NAME }}.app" | cut -f1)"
          [ -f dist/*.dmg ] && echo "DMG size: $(du -sh dist/*.dmg | cut -f1)"

      # Prepare artifacts with consistent naming
      - name: Prepare artifacts
        id: prepare
        run: |
          mkdir -p artifacts

          # Get version from pyproject.toml
          VERSION=$(uv run python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")

          # Determine build identifier based on trigger
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            # Tag builds: clean version (official release)
            BUILD_ID="${VERSION}"
          elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            # PR builds: add PR number
            PR_NUMBER="${{ github.event.number }}"
            BUILD_ID="${VERSION}-pr${PR_NUMBER}"
          else
            # Manual/push builds: add dev suffix
            BUILD_ID="${VERSION}-dev"
          fi

          # Create consistent naming
          ARTIFACT_FOLDER="Universal-DJ-USB-${BUILD_ID}-${{ matrix.target }}"
          CLI_NAME="udj-${BUILD_ID}-${{ matrix.target }}"

          # Export for next step
          echo "artifact_folder=$ARTIFACT_FOLDER" >> $GITHUB_OUTPUT
          echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT

          # macOS artifacts - copy CLI as-is with proper naming
          if [ -f "dist/udj" ]; then
            cp "dist/udj" "artifacts/${CLI_NAME}"
            chmod +x "artifacts/${CLI_NAME}"
          fi

          # Copy DMG files as-is (build.sh already names them correctly)
          for dmg in dist/*.dmg; do
            if [ -f "$dmg" ]; then
              cp "$dmg" "artifacts/"
            fi
          done

          # If no DMG but app bundle exists, create tar.gz with proper naming
          if [ -d "dist/${{ env.APP_NAME }}.app" ] && [ ! -f dist/*.dmg ]; then
            TARBALL_NAME="Universal-DJ-USB-${BUILD_ID}-${{ matrix.target }}.tar.gz"
            tar -czf "artifacts/${TARBALL_NAME}" -C dist "${{ env.APP_NAME }}.app"
          fi

          # Show what we created
          echo "Created artifacts:"
          ls -la artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prepare.outputs.artifact_folder }}
          path: artifacts/
          retention-days: 30
