name: Release Drafter

on:
  push:
    tags:
      - "v*" # Only trigger when tags starting with 'v' are pushed

permissions:
  contents: write

jobs:
  update_release_draft:
    permissions:
      contents: write # Required to create/update GitHub releases
      pull-requests: write # Required for autolabeler
    runs-on: ubuntu-latest
    steps:
      # Drafts release notes when tags are pushed from release.sh
      - uses: release-drafter/release-drafter@v6
        with:
          tag: ${{ github.ref_name }} # Use the pushed tag name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
